const buildLEOffer = () => {
  return {
    name: 'Five-Star Paris Art Deco Stay Near the Eiffel Tower',
    description:
      'Hidden within the striking wraparound facade of a 1930s telephone exchange, the Hôtel Le Cinq Codet has been transformed into a stylish see-and-be-seen haven in the heart of Paris.',
    location: 'La ville de la lumiere',
    highlights: '- Amazing Highlights',
    what_we_like: '- We love it all',
    facilities: 'Magnificent bathroom  ',
    status: 'content-approved',
    getting_there: 'Go left on ry hand rd',
    fine_print: 'Not good for surfers',
    sale_unit: 'room',
    booking_guarantee:
      '**7-Day Change of Mind ‘No Questions Asked’ Refund Guarantee:** Things don’t always work out. Our 7-day Change of Mind Guarantee is there to help. Bookings (except for Tour bookings and flights) may be cancelled with a full refund provided that cancellation occurs strictly within 7 days from the date of purchase and provided that the cancellation is made no less than 21 days prior to the check-in date.',
    _links: {},
    id_salesforce_external: '0060I00000eNTRSQA4',
    le_offer_id: '585085',
    satisfaction_survey_link: null,
    type: 'hotel',
    booking_type: 'reservation',
    run_date: '2019-12-04T06:07:00.000Z',
    end_date: '2019-12-18T06:07:00.000Z',
    travel_from_date: '2019-11-01',
    travel_to_date: '2021-03-31',
    book_by_date: '2021-01-29',
    slug: 'la-vile-de-la-lumiere',
    panel_cloudinary_id: 'e0nd1erdgih5fzu2w6bj',
    video_cloudinary_id: null,
    video_youtube_id: null,
    videos: {},
    vendor_account_id: '0010I000027JgqFQAS',
    vendor_contact_phone: '+33 1 53 85 15 61',
    vendor_booking_email: 'contact@le5codet.com',
    vendor_email: 'contact@le5codet.com',
    schedules: [],
    brand_schedules: [],
    surcharge_paid_direct_to_vendor: false,
    qff_enabled: true,
    upsell_text_qantas: 'Buy this and get some points',
    partnerships: [],
    memberships: [],
    tour_flight_details_required: false,
    staff_discount_enabled: true,
    no_index: false,
    enable_customer_portal_date_change: true,
    packages_count: 9,
    packages: [
      {
        _links: {},
        fk_room_type_id: '52a04cb0-3e59-11ea-80f2-ad68d677b787',
        fk_property_id: '01b96480-3e59-11ea-80f2-ad68d677b787',
        fk_room_rate_id: '198b69a7-2225-4e8f-b7a4-ebe3f4914274',
        fk_room_policy_id: 7,
        room_policy_description: 'classic room policy create',
        number_of_nights: 3,
        airport_transfers_included: false,
        max_extra_nights: 0,
        nightly_cost_price: 0,
        discount_percent: 0,
        name: '3 nights stay in a Classic Room for two',
        description: '3 nights stay in a Classic Room',
        inclusion_highlights: '',
        status: 'content-approved',
        id: 117551,
        id_salesforce_external: 'a0s0I000007Sj5JQAS',
        offer_id_salesforce_external: '0060I00000eNTRSQA4',
        prices_count: 33,
        cost_price: 530,
        cost_currency: 'EUR',
        qff_bonus_points: null,
        qff_bonus_description: null,
        regions: [],
        prices: [
          {
            currency_code: 'AUD',
            price: 1099,
            value: 2068,
            nightly_price: 0,
            nightly_value: 0,
            margin_aud: 0,
          },
        ],
        sort_order: null,
        room_occupancy: 'Two Adults',
        deal_option_name: '3 nights stay in a Classic Room for two',
        flexible_nights: false,
        addons: [],
        partnerships: [],
        is_exclusive: false,
        memberships: [],
        package_bonus_inclusions: [],
        package_options: [],
      },
      {
        _links: {},
        fk_room_type_id: '52a04cb0-3e59-11ea-80f2-ad68d677b787',
        fk_property_id: '01b96480-3e59-11ea-80f2-ad68d677b787',
        fk_room_rate_id: '198b69a7-2225-4e8f-b7a4-ebe3f4914274',
        fk_room_policy_id: 7,
        room_policy_description: 'classic room policy create',
        number_of_nights: 3,
        airport_transfers_included: false,
        max_extra_nights: 0,
        nightly_cost_price: 0,
        discount_percent: 0,
        name: '3 nights stay in an upgraded Superior room for two',
        description: '3 nights stay in a Classic Room',
        inclusion_highlights: '',
        status: 'content-approved',
        id: 117546,
        id_salesforce_external: 'a0s0I000007Sj5KQAS',
        offer_id_salesforce_external: '0060I00000eNTRSQA4',
        prices_count: 33,
        cost_price: 600,
        cost_currency: 'EUR',
        qff_bonus_points: null,
        qff_bonus_description: null,
        regions: [],
        prices: null,
        sort_order: 2,
        room_occupancy: 'Two Adults',
        deal_option_name: '3 nights stay in an upgraded Superior room for two',
        flexible_nights: false,
        addons: [],
        partnerships: [],
        is_exclusive: false,
        memberships: [],
        package_bonus_inclusions: [],
        package_options: [],
      },
      {
        _links: {},
        fk_room_type_id: '52a04cb0-3e59-11ea-80f2-ad68d677b787',
        fk_property_id: '01b96480-3e59-11ea-80f2-ad68d677b787',
        fk_room_rate_id: '198b69a7-2225-4e8f-b7a4-ebe3f4914274',
        fk_room_policy_id: 7,
        room_policy_description: 'classic room policy create',
        number_of_nights: 3,
        airport_transfers_included: false,
        max_extra_nights: 0,
        nightly_cost_price: 0,
        discount_percent: 0,
        name: '3 nights stay in a Junior Suite for two',
        description: '3 nights stay in a Classic Room',
        inclusion_highlights: '',
        status: 'content-approved',
        id: 117552,
        id_salesforce_external: 'a0s0I000007Sj5LQAS',
        offer_id_salesforce_external: '0060I00000eNTRSQA4',
        prices_count: 33,
        cost_price: 950,
        cost_currency: 'EUR',
        qff_bonus_points: null,
        qff_bonus_description: null,
        regions: [],
        prices: [
          {
            currency_code: 'AUD',
            price: 1999,
            value: 2829,
            nightly_price: 0,
            nightly_value: 0,
            margin_aud: 0,
          },
        ],
        sort_order: 2,
        room_occupancy: 'Two Adults',
        deal_option_name: '3 nights stay in a Junior Suite for two',
        flexible_nights: false,
        addons: [],
        partnerships: [],
        is_exclusive: false,
        memberships: [],
        package_bonus_inclusions: [],
        package_options: [],
      },
      {
        _links: {},
        fk_room_type_id: '52a04cb0-3e59-11ea-80f2-ad68d677b787',
        fk_property_id: '01b96480-3e59-11ea-80f2-ad68d677b787',
        fk_room_rate_id: '198b69a7-2225-4e8f-b7a4-ebe3f4914274',
        fk_room_policy_id: 7,
        room_policy_description: 'classic room policy create',
        number_of_nights: 7,
        airport_transfers_included: false,
        max_extra_nights: 0,
        nightly_cost_price: 0,
        discount_percent: 0,
        name: 'TEST',
        description: 'TEST',
        inclusion_highlights: '',
        status: 'content-approved',
        id: 117548,
        id_salesforce_external: 'a0s0I000007Sj5MQAS',
        offer_id_salesforce_external: '0060I00000eNTRSQA4',
        prices_count: 33,
        cost_price: 2130,
        cost_currency: 'EUR',
        qff_bonus_points: null,
        qff_bonus_description: null,
        regions: [],
        prices: [
          {
            currency_code: 'AUD',
            price: 4499,
            value: 6363,
            nightly_price: 0,
            nightly_value: 0,
            margin_aud: 0,
          },
        ],
        sort_order: null,
        room_occupancy: 'TEST',
        deal_option_name: '7 nights stay in a Junior Suite for two',
        flexible_nights: false,
        addons: [],
        partnerships: [],
        is_exclusive: false,
        memberships: [],
        package_bonus_inclusions: [],
        package_options: [],
      },
      {
        _links: {},
        fk_room_type_id: '52a04cb0-3e59-11ea-80f2-ad68d677b787',
        fk_property_id: '01b96480-3e59-11ea-80f2-ad68d677b787',
        fk_room_rate_id: '198b69a7-2225-4e8f-b7a4-ebe3f4914274',
        fk_room_policy_id: 7,
        room_policy_description: 'classic room policy create',
        number_of_nights: 4,
        airport_transfers_included: false,
        max_extra_nights: 0,
        nightly_cost_price: 0,
        discount_percent: 0,
        name: '4 nights stay in a Classic Room for two',
        description: '3 nights stay in a Classic Room',
        inclusion_highlights: '',
        status: 'content-approved',
        id: 117553,
        id_salesforce_external: 'a0s0I000007Sj5NQAS',
        offer_id_salesforce_external: '0060I00000eNTRSQA4',
        prices_count: 33,
        cost_price: 700,
        cost_currency: 'EUR',
        qff_bonus_points: null,
        qff_bonus_description: null,
        regions: [],
        prices: [
          {
            currency_code: 'AUD',
            price: 1449,
            value: 2729,
            nightly_price: 100,
            nightly_value: 665,
            margin_aud: 0,
          },
        ],
        sort_order: null,
        room_occupancy: 'Two Adults',
        deal_option_name: '4 nights stay in a Classic Room for two',
        flexible_nights: false,
        addons: [],
        partnerships: [],
        is_exclusive: false,
        memberships: [],
        package_bonus_inclusions: [],
        package_options: [],
      },
      {
        _links: {},
        fk_room_type_id: '52a04cb0-3e59-11ea-80f2-ad68d677b787',
        fk_property_id: '01b96480-3e59-11ea-80f2-ad68d677b787',
        fk_room_rate_id: '198b69a7-2225-4e8f-b7a4-ebe3f4914274',
        fk_room_policy_id: 7,
        room_policy_description: 'classic room policy create',
        number_of_nights: 4,
        airport_transfers_included: false,
        max_extra_nights: 0,
        nightly_cost_price: 0,
        discount_percent: 0,
        name: '4 nights stay in an upgraded Superior room for two',
        description: '3 nights stay in a Classic Room',
        inclusion_highlights: '',
        status: 'content-approved',
        id: 117547,
        id_salesforce_external: 'a0s0I000007Sj5OQAS',
        offer_id_salesforce_external: '0060I00000eNTRSQA4',
        prices_count: 33,
        cost_price: 790,
        cost_currency: 'EUR',
        qff_bonus_points: null,
        qff_bonus_description: null,
        regions: [],
        prices: [
          {
            currency_code: 'AUD',
            price: 1699,
            value: 2961,
            nightly_price: 120,
            nightly_value: 723,
            margin_aud: 0,
          },
        ],
        sort_order: null,
        room_occupancy: 'Two Adults',
        deal_option_name: '4 nights stay in an upgraded Superior room for two',
        flexible_nights: false,
        addons: [],
        partnerships: [],
        is_exclusive: false,
        memberships: [],
        package_bonus_inclusions: [],
        package_options: [],
      },
      {
        _links: {},
        fk_room_type_id: '52a04cb0-3e59-11ea-80f2-ad68d677b787',
        fk_property_id: '01b96480-3e59-11ea-80f2-ad68d677b787',
        fk_room_rate_id: '198b69a7-2225-4e8f-b7a4-ebe3f4914274',
        fk_room_policy_id: 7,
        room_policy_description: 'classic room policy create',
        number_of_nights: 4,
        airport_transfers_included: false,
        max_extra_nights: 0,
        nightly_cost_price: 0,
        discount_percent: 0,
        name: '4 nights stay in a Junior Suite for two',
        description:
          '- **Inclusions valid for two adults** - Daily breakfast at Chiquette Restaurant - A glass of champagne each - A welcome box of chocolates on arrival',
        inclusion_highlights: '',
        status: 'content-approved',
        id: 117545,
        id_salesforce_external: 'a0s0I000007Sj5PQAS',
        offer_id_salesforce_external: '0060I00000eNTRSQA4',
        prices_count: 33,
        cost_price: 1250,
        cost_currency: 'EUR',
        qff_bonus_points: null,
        qff_bonus_description: null,
        regions: [],
        prices: [
          {
            currency_code: 'AUD',
            price: 2599,
            value: 3706,
            nightly_price: 150,
            nightly_value: 882,
            margin_aud: 0,
          },
        ],
        sort_order: null,
        room_occupancy: 'Two Adults',
        deal_option_name: '4 nights stay in a Junior Suite for two',
        flexible_nights: false,
        addons: [],
        partnerships: [],
        is_exclusive: false,
        memberships: [],
        package_bonus_inclusions: [],
        package_options: [],
      },
      {
        _links: {},
        fk_room_type_id: '52a04cb0-3e59-11ea-80f2-ad68d677b787',
        fk_property_id: '01b96480-3e59-11ea-80f2-ad68d677b787',
        fk_room_rate_id: '198b69a7-2225-4e8f-b7a4-ebe3f4914274',
        fk_room_policy_id: 7,
        room_policy_description: 'classic room policy create',
        number_of_nights: 7,
        airport_transfers_included: false,
        max_extra_nights: 0,
        nightly_cost_price: 0,
        discount_percent: 0,
        name: '7 nights stay in a Classic Room for two',
        description: '3 nights stay in a Classic Room',
        inclusion_highlights: '',
        status: 'content-approved',
        id: 117549,
        id_salesforce_external: 'a0s0I000007Sj5QQAS',
        offer_id_salesforce_external: '0060I00000eNTRSQA4',
        prices_count: 33,
        cost_price: 1175,
        cost_currency: 'EUR',
        qff_bonus_points: null,
        qff_bonus_description: null,
        regions: [],
        prices: [],
        sort_order: null,
        room_occupancy: 'Two Adults',
        deal_option_name: '7 nights stay in a Classic Room for two',
        flexible_nights: false,
        addons: [],
        partnerships: [],
        is_exclusive: false,
        memberships: [],
        package_bonus_inclusions: [],
        package_options: [],
      },
      {
        _links: {},
        fk_room_type_id: '52a04cb0-3e59-11ea-80f2-ad68d677b787',
        fk_property_id: '01b96480-3e59-11ea-80f2-ad68d677b787',
        fk_room_rate_id: '198b69a7-2225-4e8f-b7a4-ebe3f4914274',
        fk_room_policy_id: 7,
        room_policy_description: 'classic room policy create',
        number_of_nights: 7,
        airport_transfers_included: false,
        max_extra_nights: 2,
        nightly_cost_price: 0,
        discount_percent: 0,
        name: '7 nights stay in an upgraded Superior room for two',
        description: '3 nights stay in a Classic Room',
        inclusion_highlights: '',
        status: 'content-approved',
        id: 117550,
        id_salesforce_external: 'a0s0I000007Sj5RQAS',
        offer_id_salesforce_external: '0060I00000eNTRSQA4',
        prices_count: 33,
        cost_price: 1360,
        cost_currency: 'EUR',
        qff_bonus_points: null,
        qff_bonus_description: null,
        regions: [],
        prices: [
          {
            currency_code: 'AUD',
            price: 2899,
            value: 5137,
            nightly_price: 0,
            nightly_value: 0,
            margin_aud: 0,
          },
        ],
        sort_order: null,
        room_occupancy: 'Two Adults',
        deal_option_name: '7 nights stay in an upgraded Superior room for two',
        flexible_nights: true,
        addons: [],
        partnerships: [],
        is_exclusive: false,
        memberships: [],
        package_bonus_inclusions: [],
        package_options: [],
      },
    ],
    images_count: 8,
    images: [],
    locations: [],
    flights_enabled: true,
    flights_cache_disabled: false,
    flights_max_arrival_time: '23:45',
    flights_min_returning_departure_time: '07:00',
    flight_regions: [],
    flight_destination_port: 'CDG',
    flights_warning_enabled: true,
    flights_warning_headline: null,
    flights_warning_popup_body: 'HEy man sorry for that',
    flexible_nights: true,
    insurance_countries: [],
    holiday_types: [],
    campaigns: null,
    display_value: true,
    subject_line: "Vive l' amoure",
    preheader: 'La ville de la lumiere',
    redemption_options: [],
    refunds_not_permitted: false,
    sf_brands: [],
    le_contracts_geo: 'International',
    payment_milestone: '100',
    payment_method: null,
    on_hold_settings: null,
    date_change_settings: null,
    latest_departure_date_change_allowed: null,
    offer_tile_inclusion_heading: null,
    offer_tile_inclusions: null,
    additional_description: null,
    campaign_type: null,
    days_before_check_in_changes_disallowed: 1,
  }
}

const buildLEPackageWithLuxPlusPricing =       {
  _links: {},
  fk_room_type_id: '52a04cb0-3e59-11ea-80f2-ad68d677b787',
  fk_property_id: '01b96480-3e59-11ea-80f2-ad68d677b787',
  fk_room_rate_id: '198b69a7-2225-4e8f-b7a4-ebe3f4914274',
  fk_room_policy_id: 7,
  room_policy_description: 'classic room policy create',
  number_of_nights: 7,
  airport_transfers_included: false,
  max_extra_nights: 2,
  nightly_cost_price: 0,
  discount_percent: 0,
  name: '7 nights stay in an upgraded Superior room for two',
  description: '3 nights stay in a Classic Room',
  inclusion_highlights: '',
  status: 'content-approved',
  id: 117550,
  id_salesforce_external: 'a0s0I000007Sj5RQAS',
  offer_id_salesforce_external: '0060I00000eNTRSQA4',
  prices_count: 33,
  cost_price: 1360,
  cost_currency: 'EUR',
  qff_bonus_points: null,
  qff_bonus_description: null,
  regions: [],
  prices: [
    {
      currency_code: 'AUD',
      price: 2899,
      lux_plus_price: 2500,
      value: 5137,
      nightly_price: 400,
      lux_plus_nightly_price: 350,
      nightly_value: 800,
      margin_aud: 0,
    },
  ],
  sort_order: null,
  room_occupancy: 'Two Adults',
  deal_option_name: '7 nights stay in an upgraded Superior room for two',
  flexible_nights: true,
  addons: [],
  partnerships: [],
  is_exclusive: false,
  memberships: [],
  package_bonus_inclusions: [],
  package_options: [],
}

const buildLEPackageWithOnlyLuxPlusPriceNoNightlyPrice =       {
  _links: {},
  fk_room_type_id: '52a04cb0-3e59-11ea-80f2-ad68d677b787',
  fk_property_id: '01b96480-3e59-11ea-80f2-ad68d677b787',
  fk_room_rate_id: '198b69a7-2225-4e8f-b7a4-ebe3f4914274',
  fk_room_policy_id: 7,
  room_policy_description: 'classic room policy create',
  number_of_nights: 7,
  airport_transfers_included: false,
  max_extra_nights: 2,
  nightly_cost_price: 0,
  discount_percent: 0,
  name: '7 nights stay in an upgraded Superior room for two',
  description: '3 nights stay in a Classic Room',
  inclusion_highlights: '',
  status: 'content-approved',
  id: 117550,
  id_salesforce_external: 'a0s0I000007Sj5RQAS',
  offer_id_salesforce_external: '0060I00000eNTRSQA4',
  prices_count: 33,
  cost_price: 1360,
  cost_currency: 'EUR',
  qff_bonus_points: null,
  qff_bonus_description: null,
  regions: [],
  prices: [
    {
      currency_code: 'AUD',
      price: 2899,
      lux_plus_price: 2500,
      value: 5137,
      nightly_price: 400,
      lux_plus_nightly_price: 0,
      nightly_value: 800,
      margin_aud: 0,
    },
  ],
  sort_order: null,
  room_occupancy: 'Two Adults',
  deal_option_name: '7 nights stay in an upgraded Superior room for two',
  flexible_nights: true,
  addons: [],
  partnerships: [],
  is_exclusive: false,
  memberships: [],
  package_bonus_inclusions: [],
  package_options: [],
}

module.exports = {
  buildLEOffer,
  buildLEPackageWithLuxPlusPricing,
  buildLEPackageWithOnlyLuxPlusPriceNoNightlyPrice,
}
