const buildLMEOffer = () => {
  return {
    name: '[E2E test - do not change] - Last minute hotel reservation',
    description:
      'Discover the height of opulence at Mulia Villas, Nusa Dua. Be made to feel like a true VIP with 24-hour butler service, daily breakfasts, two indulgent dinners, return private airport transfers, daily cocktails and canapés and more. Located on white-sand beachfront, the award-winning complex also boast six swimming pools, a host of restaurants and bars, award-winning spa with Asia’s first ice-room and more.',
    location: 'Mulia Villas',
    highlights: '',
    what_we_like: 'what we like',
    facilities: 'shower',
    status: 'content-approved',
    getting_there:
      'Getting to Koh Samui is easy. Regular flights to Bangkok are available with Qantas, Emirates and Thai Airways, departing most Australian capital cities with an approximate flight time of 9.5 hours.',
    id_salesforce_external: '0060T000002KpfcQAC',
    le_offer_id: '585888',
    satisfaction_survey_link: 'https://www.research.net/r/T6N35KC',
    type: 'last_minute_hotel',
    booking_type: 'reservation',
    run_date: '2020-06-03T01:09:00.000Z',
    end_date: '2021-06-03T01:09:00.000Z',
    travel_from_date: '2020-06-03',
    travel_to_date: '2025-06-30',
    book_by_date: '2024-03-26',
    slug: 'nightly-rates-opp-please-do-ignore',
    panel_cloudinary_id: null,
    video_cloudinary_id: null,
    video_youtube_id: '7l9hiPdfroI',
    videos: {},
    vendor_account_id: '00128000005c1SvAAI',
    vendor_contact_phone: '+61430905037',
    vendor_booking_email: 'vendor-189834@inbox.mailtrap.io',
    vendor_email: 'vendor-189834@inbox.mailtrap.io',
    schedules: [],
    brand_schedules: [],
    surcharge_paid_direct_to_vendor: false,
    qff_enabled: false,
    upsell_text_qantas: '',
    partnerships: [],
    memberships: [],
    tour_flight_details_required: false,
    staff_discount_enabled: true,
    no_index: false,
    enable_customer_portal_date_change: false,
    packages_count: 3,
    packages: [
      {
        _links: {},
        fk_room_type_id: '7227c6c0-8411-11e8-a9a2-0396cc09a4e4',
        fk_property_id: '16adf5d0-8411-11e8-a9a2-0396cc09a4e4',
        fk_room_rate_id: '30192905-0266-47fb-a4f4-62d71dbb8557',
        fk_room_policy_id: null,
        room_policy_description: null,
        number_of_nights: 1,
        airport_transfers_included: false,
        max_extra_nights: 0,
        nightly_cost_price: 0,
        discount_percent: 0,
        name: 'Nightly Rates Sub marin room',
        description: 'Nightly Rates E2E',
        inclusion_highlights:
          '- A$40 food and drink credit per room - Complimentary in-room movies - Guaranteed 1pm late checkout',
        status: 'content-approved',
        id: 117574,
        id_salesforce_external: 'a0s0T0000006xxGQAQ',
        offer_id_salesforce_external: '0060T000002KpfcQAC',
        prices_count: 33,
        cost_price: 400,
        cost_currency: 'AUD',
        qff_bonus_points: null,
        qff_bonus_description: null,
        regions: ['world'],
        prices: [
          {
            currency_code: 'AUD',
            price: 240,
            value: 300,
            nightly_price: 0,
            nightly_value: 0,
          },
        ],
        sort_order: null,
        room_occupancy: 'Two Adults minimum',
        deal_option_name: 'Nightly Rates Sub marin room',
        flexible_nights: false,
        addons: [],
        partnerships: [],
        is_exclusive: false,
        memberships: [],
        package_bonus_inclusions: [],
        package_options: [
          {
            id: '2c533fd7-85d6-4493-b52a-08fd52a96632',
            fk_room_rate_id: '30192905-0266-47fb-a4f4-62d71dbb8557',
            name: 'Free drinks',
          },
        ],
      },
      {
        _links: {},
        fk_room_type_id: '100ebef0-6c1e-11e7-80aa-03af88b051d5',
        fk_property_id: '16adf5d0-8411-11e8-a9a2-0396cc09a4e4',
        fk_room_rate_id: '239de647-1a38-4b46-9b50-d5254296491e',
        fk_room_policy_id: 2,
        room_policy_description:
          '**Room Policy test last minuteeeeee?test updatee**',
        number_of_nights: 1,
        airport_transfers_included: false,
        max_extra_nights: 0,
        nightly_cost_price: 0,
        discount_percent: 0,
        name: 'Nightly Rates Room With Rates',
        description: 'Nightly Rates E2E',
        inclusion_highlights:
          '- A$40 food and drink credit per room - Complimentary in-room movies - Guaranteed 1pm late checkout',
        status: 'content-approved',
        id: 117575,
        id_salesforce_external: 'a0s0T0000006xxBQAQ',
        offer_id_salesforce_external: '0060T000002KpfcQAC',
        prices_count: 33,
        cost_price: 200,
        cost_currency: 'AUD',
        qff_bonus_points: null,
        qff_bonus_description: null,
        regions: [],
        prices: [
          {
            currency_code: 'AUD',
            price: 120,
            value: 200,
            nightly_price: 0,
            nightly_value: 0,
          },
        ],
        sort_order: null,
        room_occupancy: 'Two Adults',
        deal_option_name: 'Nightly Rates Room With Rates',
        flexible_nights: false,
        addons: [],
        partnerships: [],
        is_exclusive: false,
        memberships: [],
        package_bonus_inclusions: [],
        package_options: [],
      },
      {
        _links: {},
        fk_room_type_id: '100ebef0-6c1e-11e7-80aa-03af88b051d5',
        fk_property_id: '16adf5d0-8411-11e8-a9a2-0396cc09a4e4',
        fk_room_rate_id: '38b1a1d0-b4e4-11ea-8c2f-09e168d100d1',
        fk_room_policy_id: 2,
        room_policy_description:
          '**Room Policy test last minuteeeeee?test updatee**',
        number_of_nights: 1,
        airport_transfers_included: false,
        max_extra_nights: 3,
        nightly_cost_price: 0,
        discount_percent: 0,
        name: 'Nightly Rates E2E',
        description: 'Nightly Rates E2E',
        inclusion_highlights:
          '- A$40 food and drink credit per room - Complimentary in-room movies - Guaranteed 1pm late checkout',
        status: 'content-approved',
        id: 117573,
        id_salesforce_external: 'a0s0T0000006xx6QAA',
        offer_id_salesforce_external: '0060T000002KpfcQAC',
        prices_count: 33,
        cost_price: 100,
        cost_currency: 'AUD',
        qff_bonus_points: null,
        qff_bonus_description: null,
        regions: [],
        prices: [
          {
            currency_code: 'AUD',
            price: 120,
            value: 200,
            nightly_price: 0,
            nightly_value: 0,
          },
        ],
        sort_order: null,
        room_occupancy: 'Two Adults',
        deal_option_name: 'Nightly Rates E2E',
        flexible_nights: true,
        addons: [],
        partnerships: [],
        is_exclusive: false,
        memberships: [],
        package_bonus_inclusions: [],
        package_options: [],
      },
    ],
    images_count: 7,
    images: [],
    locations: [],
    flights_enabled: false,
    flights_cache_disabled: false,
    flights_max_arrival_time: null,
    flights_min_returning_departure_time: null,
    flight_regions: [],
    flight_destination_port: null,
    flights_warning_enabled: false,
    flights_warning_headline: null,
    flights_warning_popup_body: null,
    flexible_nights: true,
    insurance_countries: [],
    holiday_types: [],
    campaigns: null,
    display_value: true,
    subject_line: '',
    preheader: '',
    redemption_options: [],
    refunds_not_permitted: false,
    sf_brands: [],
    le_contracts_geo: null,
    payment_milestone: null,
    payment_method: null,
    on_hold_settings: null,
    date_change_settings: null,
    latest_departure_date_change_allowed: null,
    offer_tile_inclusion_heading: 'Lux Premium inclusions:',
    offer_tile_inclusions: '- test inclusions 1',
    additional_description: null,
    campaign_type: null,
    days_before_check_in_changes_disallowed: 5,
  }
}

module.exports = {
  buildLMEOffer,
}
