const buildTAOOffer = () => {
  return {
    name:
      'P&O Cruise - Dep Ex Sydney - 29 March 2019 - Comedy - Pacific Explorer X917 (SCOOPON)',
    description: null,
    location: null,
    highlights: null,
    what_we_like: '',
    facilities: '',
    status: 'draft',
    getting_there: '',
    fine_print: '',
    sale_unit: 'room',
    booking_guarantee:
      '**7-Day Change of Mind ‘No Questions Asked’ Refund Guarantee:** Things don’t always work out. Our 7-day Change of Mind Guarantee is there to help. Bookings (except for Tour bookings and flights) may be cancelled with a full refund provided that cancellation occurs strictly within 7 days from the date of purchase and provided that the cancellation is made no less than 21 days prior to the check-in date.',
    _links: {},
    id_salesforce_external: '0060I00000ZoqQsQAJ',
    le_offer_id: '566343',
    satisfaction_survey_link: null,
    type: 'tactical_ao_hotel',
    booking_type: 'voucher',
    run_date: null,
    end_date: null,
    travel_from_date: '2019-03-29',
    travel_to_date: '2019-04-01',
    book_by_date: '2019-02-04',
    slug:
      'pando-cruise-dep-ex-sydney-29-march-2019-comedy-pacific-explorer-x917-scoopon',
    panel_cloudinary_id: null,
    video_cloudinary_id: null,
    video_youtube_id: null,
    videos: {},
    vendor_account_id: '0010I00001o5VSjQAM',
    vendor_contact_phone: null,
    vendor_booking_email: 'cruiseteam@luxuryescapes.com',
    vendor_email: 'cruiseteam@luxuryescapes.com',
    schedules: [],
    brand_schedules: [],
    surcharge_paid_direct_to_vendor: false,
    qff_enabled: false,
    upsell_text_qantas: '',
    partnerships: [],
    memberships: [],
    tour_flight_details_required: false,
    staff_discount_enabled: true,
    no_index: false,
    enable_customer_portal_date_change: true,
    packages_count: 7,
    packages: [
      {
        _links: {},
        fk_room_type_id: null,
        fk_property_id: null,
        fk_room_rate_id: null,
        fk_room_policy_id: null,
        room_policy_description: null,
        number_of_nights: 4,
        airport_transfers_included: false,
        max_extra_nights: 0,
        nightly_cost_price: 0,
        discount_percent: 0,
        name: '1 Person Quad Share Interior',
        description: '1 Person Quad Share Interior',
        inclusion_highlights: null,
        status: 'draft',
        id: null,
        id_salesforce_external: 'a0s0I000005o8d3QAA',
        offer_id_salesforce_external: '0060I00000ZoqQsQAJ',
        prices_count: 33,
        cost_price: 235.2,
        cost_currency: 'AUD',
        qff_bonus_points: null,
        qff_bonus_description: null,
        regions: ['world'],
        prices: [
          {
            currency_code: 'AUD',
            price: 299,
            value: 419,
            nightly_price: 0,
            nightly_value: 0,
          },
        ],
        sort_order: null,
        room_occupancy: 'Two Adults',
        deal_option_name: '1 Person Quad Share Interior',
        flexible_nights: null,
        addons: [],
        partnerships: [],
        is_exclusive: false,
        memberships: [],
        package_bonus_inclusions: [],
        package_options: [],
      },
      {
        _links: {},
        fk_room_type_id: null,
        fk_property_id: null,
        fk_room_rate_id: null,
        fk_room_policy_id: null,
        room_policy_description: null,
        number_of_nights: 4,
        airport_transfers_included: false,
        max_extra_nights: 0,
        nightly_cost_price: 0,
        discount_percent: 0,
        name: '1 Person Quad Share Ocean View',
        description: '1 Person Quad Share Ocean View',
        inclusion_highlights: null,
        status: 'draft',
        id: null,
        id_salesforce_external: 'a0s0I000005o8d8QAA',
        offer_id_salesforce_external: '0060I00000ZoqQsQAJ',
        prices_count: 33,
        cost_price: 299.5,
        cost_currency: 'AUD',
        qff_bonus_points: null,
        qff_bonus_description: null,
        regions: [],
        prices: [
          {
            currency_code: 'AUD',
            price: 349,
            value: 469,
            nightly_price: 0,
            nightly_value: 0,
          },
        ],
        sort_order: null,
        room_occupancy: 'Two Adults',
        deal_option_name: '1 Person Quad Share Ocean View',
        flexible_nights: null,
        addons: [],
        partnerships: [],
        is_exclusive: false,
        memberships: [],
        package_bonus_inclusions: [],
        package_options: [],
      },
      {
        _links: {},
        fk_room_type_id: null,
        fk_property_id: null,
        fk_room_rate_id: null,
        fk_room_policy_id: null,
        room_policy_description: null,
        number_of_nights: 4,
        airport_transfers_included: false,
        max_extra_nights: 0,
        nightly_cost_price: 0,
        discount_percent: 0,
        name: '1 Person Quad Share Balcony',
        description: '1 Person Quad Share Balcony',
        inclusion_highlights: null,
        status: 'draft',
        id: null,
        id_salesforce_external: 'a0s0I000005o8dDQAQ',
        offer_id_salesforce_external: '0060I00000ZoqQsQAJ',
        prices_count: 33,
        cost_price: 344,
        cost_currency: 'AUD',
        qff_bonus_points: null,
        qff_bonus_description: null,
        regions: [],
        prices: [
          {
            currency_code: 'AUD',
            price: 399,
            value: 529,
            nightly_price: 0,
            nightly_value: 0,
          },
        ],
        sort_order: null,
        room_occupancy: 'Two Adults',
        deal_option_name: '1 Person Quad Share Balcony',
        flexible_nights: null,
        addons: [],
        partnerships: [],
        is_exclusive: false,
        memberships: [],
        package_bonus_inclusions: [],
        package_options: [],
      },
      {
        _links: {},
        fk_room_type_id: null,
        fk_property_id: null,
        fk_room_rate_id: null,
        fk_room_policy_id: null,
        room_policy_description: null,
        number_of_nights: 4,
        airport_transfers_included: false,
        max_extra_nights: 0,
        nightly_cost_price: 0,
        discount_percent: 0,
        name: '1 Person Twin Share Interior',
        description: '1 Person Twin Share Interior',
        inclusion_highlights: null,
        status: 'draft',
        id: null,
        id_salesforce_external: 'a0s0I000005o8dNQAQ',
        offer_id_salesforce_external: '0060I00000ZoqQsQAJ',
        prices_count: 33,
        cost_price: 279.7,
        cost_currency: 'AUD',
        qff_bonus_points: null,
        qff_bonus_description: null,
        regions: [],
        prices: [
          {
            currency_code: 'AUD',
            price: 349,
            value: 529,
            nightly_price: 0,
            nightly_value: 0,
          },
        ],
        sort_order: null,
        room_occupancy: 'Two Adults',
        deal_option_name: '1 Person Twin Share Interior',
        flexible_nights: null,
        addons: [],
        partnerships: [],
        is_exclusive: false,
        memberships: [],
        package_bonus_inclusions: [],
        package_options: [],
      },
      {
        _links: {},
        fk_room_type_id: null,
        fk_property_id: null,
        fk_room_rate_id: null,
        fk_room_policy_id: null,
        room_policy_description: null,
        number_of_nights: 4,
        airport_transfers_included: false,
        max_extra_nights: 0,
        nightly_cost_price: 0,
        discount_percent: 0,
        name: '1 Person Twin Share Ocean View',
        description: '1 Person Twin Share Ocean View',
        inclusion_highlights: null,
        status: 'draft',
        id: null,
        id_salesforce_external: 'a0s0I000005o8dXQAQ',
        offer_id_salesforce_external: '0060I00000ZoqQsQAJ',
        prices_count: 33,
        cost_price: 370.7,
        cost_currency: 'AUD',
        qff_bonus_points: null,
        qff_bonus_description: null,
        regions: [],
        prices: [
          {
            currency_code: 'AUD',
            price: 429,
            value: 589,
            nightly_price: 0,
            nightly_value: 0,
          },
        ],
        sort_order: null,
        room_occupancy: 'Two Adults',
        deal_option_name: '1 Person Twin Share Ocean View',
        flexible_nights: null,
        addons: [],
        partnerships: [],
        is_exclusive: false,
        memberships: [],
        package_bonus_inclusions: [],
        package_options: [],
      },
      {
        _links: {},
        fk_room_type_id: null,
        fk_property_id: null,
        fk_room_rate_id: null,
        fk_room_policy_id: null,
        room_policy_description: null,
        number_of_nights: 4,
        airport_transfers_included: false,
        max_extra_nights: 0,
        nightly_cost_price: 0,
        discount_percent: 0,
        name: '1 Person Twin Share Balcony',
        description: '1 Person Twin Share Balcony',
        inclusion_highlights: null,
        status: 'draft',
        id: null,
        id_salesforce_external: 'a0s0I000005o8dcQAA',
        offer_id_salesforce_external: '0060I00000ZoqQsQAJ',
        prices_count: 33,
        cost_price: 413.2,
        cost_currency: 'AUD',
        qff_bonus_points: null,
        qff_bonus_description: null,
        regions: [],
        prices: [
          {
            currency_code: 'AUD',
            price: 499,
            value: 649,
            nightly_price: 0,
            nightly_value: 0,
          },
        ],
        sort_order: null,
        room_occupancy: 'Two Adults',
        deal_option_name: '1 Person Twin Share Balcony',
        flexible_nights: null,
        addons: [],
        partnerships: [],
        is_exclusive: false,
        memberships: [],
        package_bonus_inclusions: [],
        package_options: [],
      },
      {
        _links: {},
        fk_room_type_id: null,
        fk_property_id: null,
        fk_room_rate_id: null,
        fk_room_policy_id: null,
        room_policy_description: null,
        number_of_nights: 4,
        airport_transfers_included: false,
        max_extra_nights: 1,
        nightly_cost_price: 0,
        discount_percent: 0,
        name: '1 Person Twin Share Mini Suite',
        description: '1 Person Twin Share Mini Suite',
        inclusion_highlights: null,
        status: 'draft',
        id: null,
        id_salesforce_external: 'a0s0I000005o8dhQAA',
        offer_id_salesforce_external: '0060I00000ZoqQsQAJ',
        prices_count: 33,
        cost_price: 727.7,
        cost_currency: 'AUD',
        qff_bonus_points: null,
        qff_bonus_description: null,
        regions: [],
        prices: [
          {
            currency_code: 'AUD',
            price: 819,
            value: 1029,
            nightly_price: 0,
            nightly_value: 0,
          },
        ],
        sort_order: null,
        room_occupancy: 'Two Adults',
        deal_option_name: '1 Person Twin Share Mini Suite',
        flexible_nights: true,
        addons: [],
        partnerships: [],
        is_exclusive: false,
        memberships: [],
        package_bonus_inclusions: [],
        package_options: [
          {
            id: 'b38d1f09-9937-4808-b96b-e92d5b3b797c',
            fk_room_rate_id: '4f0352c0-b69d-11ea-89fb-3f31a6d63976',
            name: 'Standard',
          },
          {
            id: '51ee2aa2-acdd-4262-ad4b-f8d39406758f',
            fk_room_rate_id: 'f901b1e0-b69d-11ea-89fb-3f31a6d63976',
            name: 'Standard with inclusions',
          },
          {
            id: 'ddebb810-a89d-42c1-b589-480d59fdd88d',
            fk_room_rate_id: 'f61874a0-b69d-11ea-89fb-3f31a6d63976',
            name: 'Standard with breakfast',
          },
        ],
      },
    ],
    images_count: 0,
    images: [],
    locations: null,
    flights_enabled: false,
    flights_cache_disabled: false,
    flights_max_arrival_time: null,
    flights_min_returning_departure_time: null,
    flight_regions: [],
    flight_destination_port: null,
    flights_warning_enabled: false,
    flights_warning_headline: null,
    flights_warning_popup_body: null,
    flexible_nights: false,
    insurance_countries: [],
    holiday_types: null,
    campaigns: null,
    display_value: true,
    subject_line: '',
    preheader: '',
    redemption_options: [],
    refunds_not_permitted: false,
    sf_brands: [],
    le_contracts_geo: null,
    payment_milestone: null,
    payment_method: null,
    on_hold_settings: null,
    date_change_settings: null,
    latest_departure_date_change_allowed: null,
    offer_tile_inclusion_heading: null,
    offer_tile_inclusions: null,
    additional_description: null,
    campaign_type: null,
    days_before_check_in_changes_disallowed: 0,
  }
}

module.exports = {
  buildTAOOffer,
}
