const buildTourOffer = () => {
  return {
    name: 'MSC Seaview - Barcelona rtn - April-July 20 Tour & Cruise Combo',
    description: '- test - also test - test again',
    location: 'Test',
    highlights: 'test',
    what_we_like: 'test',
    facilities: 'test',
    status: 'content-approved',
    getting_there: 'test',
    fine_print: 'test',
    sale_unit: 'person',
    booking_guarantee:
      '**7-Day Change of Mind ‘No Questions Asked’ Refund Guarantee:** Things don’t always work out. Our 7-day Change of Mind Guarantee is there to help. Bookings (except for Tour bookings and flights) may be cancelled with a full refund provided that cancellation occurs strictly within 7 days from the date of purchase and provided that the cancellation is made no less than 21 days prior to the check-in date.',
    _links: {},
    id_salesforce_external: '0060I00000dafNxQAI',
    le_offer_id: '580982',
    satisfaction_survey_link: null,
    type: 'tour',
    booking_type: 'reservation',
    run_date: '2019-09-26T07:30:00.000Z',
    end_date: '2019-10-17T06:30:00.000Z',
    travel_from_date: '2020-04-05',
    travel_to_date: '2020-06-13',
    book_by_date: '2019-10-28',
    slug: 'msc-seaview-barcelona',
    panel_cloudinary_id: 'r12m9cxtvoxyzsbdvi0b',
    video_cloudinary_id: null,
    video_youtube_id: null,
    videos: {},
    vendor_account_id: '0010I00001i21DcQAI',
    vendor_contact_phone: null,
    vendor_booking_email: 'cruiseteam@luxuryescapes.com',
    vendor_email: 'cruiseteam@luxuryescapes.com',
    schedules: [],
    brand_schedules: [],
    surcharge_paid_direct_to_vendor: false,
    qff_enabled: false,
    upsell_text_qantas: '',
    partnerships: [],
    memberships: [],
    tour_flight_details_required: false,
    staff_discount_enabled: true,
    no_index: false,
    enable_customer_portal_date_change: true,
    packages_count: 14,
    packages: [
      {
        _links: {},
        fk_tour_option_id: null,
        fk_tour_id: null,
        number_of_days: 21,
        name: '1 Person Twin Share Balcony Fantastica Low Season',
        description: '1 Person Twin Share Balcony Fantastica Low Season',
        inclusion_highlights: 'test copy',
        status: 'draft',
        id: 117661,
        id_salesforce_external: 'a0s0I000006zVg2QAE',
        offer_id_salesforce_external: '0060I00000dafNxQAI',
        prices_count: 33,
        cost_price: 4313.65,
        cost_currency: 'AUD',
        qff_bonus_points: null,
        qff_bonus_description: null,
        regions: [],
        prices: [
          {
            currency_code: 'AUD',
            price: 5099,
            value: 6168,
            nightly_price: 0,
            nightly_value: 0,
          },
        ],
        sort_order: null,
        room_occupancy: 'Two Adults',
        deal_option_name: '1 Person Twin Share Balcony Fantastica Low Season',
        flexible_nights: false,
        partnerships: [],
        is_exclusive: false,
        memberships: [],
        addons: [],
      },
      {
        _links: {},
        fk_tour_option_id: null,
        fk_tour_id: null,
        number_of_days: 21,
        name: '1 Person Twin Share Balcony Aurea Low Season',
        description: '1 Person Twin Share Balcony Aurea Low Season',
        inclusion_highlights: 'test copy',
        status: 'draft',
        id: 117663,
        id_salesforce_external: 'a0s0I000006zVgHQAU',
        offer_id_salesforce_external: '0060I00000dafNxQAI',
        prices_count: 33,
        cost_price: 4934.15,
        cost_currency: 'AUD',
        qff_bonus_points: null,
        qff_bonus_description: null,
        regions: [],
        prices: [
          {
            currency_code: 'AUD',
            price: 5699,
            value: 6938,
            nightly_price: 0,
            nightly_value: 0,
          },
        ],
        sort_order: null,
        room_occupancy: 'Two Adults',
        deal_option_name: '1 Person Twin Share Balcony Aurea Low Season',
        flexible_nights: false,
        partnerships: [],
        is_exclusive: false,
        memberships: [],
        addons: [],
      },
      {
        _links: {},
        fk_tour_option_id: null,
        fk_tour_id: null,
        number_of_days: 21,
        name: '1 Person Twin Share Suite Fantastica Low Season',
        description: '1 Person Twin Share Suite Fantastica Low Season',
        inclusion_highlights: 'test copy',
        status: 'draft',
        id: 117659,
        id_salesforce_external: 'a0s0I000006zVgWQAU',
        offer_id_salesforce_external: '0060I00000dafNxQAI',
        prices_count: 33,
        cost_price: 4517.65,
        cost_currency: 'AUD',
        qff_bonus_points: null,
        qff_bonus_description: null,
        regions: [],
        prices: [
          {
            currency_code: 'AUD',
            price: 5289,
            value: 6418,
            nightly_price: 0,
            nightly_value: 0,
          },
        ],
        sort_order: null,
        room_occupancy: 'Two Adults',
        deal_option_name: '1 Person Twin Share Suite Fantastica Low Season',
        flexible_nights: false,
        partnerships: [],
        is_exclusive: false,
        memberships: [],
        addons: [],
      },
      {
        _links: {},
        fk_tour_option_id: null,
        fk_tour_id: null,
        number_of_days: 21,
        name: '1 Person Twin Share Suite Aurea Low Season',
        description: '1 Person Twin Share Suite Aurea Low Season',
        inclusion_highlights: 'test copy',
        status: 'draft',
        id: 117664,
        id_salesforce_external: 'a0s0I000006zVgbQAE',
        offer_id_salesforce_external: '0060I00000dafNxQAI',
        prices_count: 33,
        cost_price: 5138.15,
        cost_currency: 'AUD',
        qff_bonus_points: null,
        qff_bonus_description: null,
        regions: [],
        prices: [
          {
            currency_code: 'AUD',
            price: 6099,
            value: 7188,
            nightly_price: 0,
            nightly_value: 0,
          },
        ],
        sort_order: null,
        room_occupancy: 'Two Adults',
        deal_option_name: '1 Person Twin Share Suite Aurea Low Season',
        flexible_nights: false,
        partnerships: [],
        is_exclusive: false,
        memberships: [],
        addons: [],
      },
      {
        _links: {},
        fk_tour_option_id: null,
        fk_tour_id: null,
        number_of_days: 21,
        name: '1 Person Twin Share Deluxe Suite Yacht Club Low Season',
        description: '1 Person Twin Share Deluxe Suite Yacht Club Low Season',
        inclusion_highlights: 'test copy',
        status: 'draft',
        id: 117656,
        id_salesforce_external: 'a0s0I000006zVggQAE',
        offer_id_salesforce_external: '0060I00000dafNxQAI',
        prices_count: 33,
        cost_price: 5979.65,
        cost_currency: 'AUD',
        qff_bonus_points: null,
        qff_bonus_description: null,
        regions: [],
        prices: [
          {
            currency_code: 'AUD',
            price: 6955,
            value: 8188,
            nightly_price: 0,
            nightly_value: 0,
          },
        ],
        sort_order: null,
        room_occupancy: 'Two Adults',
        deal_option_name:
          '1 Person Twin Share Deluxe Suite Yacht Club Low Season',
        flexible_nights: false,
        partnerships: [],
        is_exclusive: false,
        memberships: [],
        addons: [],
      },
      {
        _links: {},
        fk_tour_option_id: '045ae9d0-5da7-11ea-a12f-0f40b52e158b',
        fk_tour_id: 'fdc100a0-5da6-11ea-a12f-0f40b52e158b',
        number_of_days: 21,
        name: '1 Person Twin Share Inside Fantastica High Season',
        description: '1 Person Twin Share Inside Fantastica High Season',
        inclusion_highlights: null,
        status: 'content-approved',
        id: 117567,
        id_salesforce_external: 'a0s0I000006zVglQAE',
        offer_id_salesforce_external: '0060I00000dafNxQAI',
        prices_count: 33,
        cost_price: 4016.15,
        cost_currency: 'AUD',
        qff_bonus_points: null,
        qff_bonus_description: null,
        regions: [],
        prices: [
          {
            currency_code: 'AUD',
            price: 4999,
            value: 5858,
            nightly_price: 0,
            nightly_value: 0,
          },
        ],
        sort_order: 1,
        room_occupancy: 'Two Adults',
        deal_option_name: '1 Person Twin Share Inside Fantastica High Season',
        flexible_nights: false,
        partnerships: [],
        is_exclusive: false,
        memberships: [],
        addons: [],
      },
      {
        _links: {},
        fk_tour_option_id: null,
        fk_tour_id: null,
        number_of_days: 21,
        name: '1 Person Twin Share Oceanview Fantastica High Season',
        description: '1 Person Twin Share Oceanview Fantastica High Season',
        inclusion_highlights: 'test copy',
        status: 'draft',
        id: 117654,
        id_salesforce_external: 'a0s0I000006zVhBQAU',
        offer_id_salesforce_external: '0060I00000dafNxQAI',
        prices_count: 33,
        cost_price: 4211.65,
        cost_currency: 'AUD',
        qff_bonus_points: null,
        qff_bonus_description: null,
        regions: [],
        prices: [
          {
            currency_code: 'AUD',
            price: 4989,
            value: 6058,
            nightly_price: 0,
            nightly_value: 0,
          },
        ],
        sort_order: null,
        room_occupancy: 'Two Adults',
        deal_option_name:
          '1 Person Twin Share Oceanview Fantastica High Season',
        flexible_nights: false,
        partnerships: [],
        is_exclusive: true,
        memberships: [],
        addons: [],
      },
      {
        _links: {},
        fk_tour_option_id: null,
        fk_tour_id: null,
        number_of_days: 21,
        name: '1 Person Twin Share Balcony Fantastica High Season',
        description: '1 Person Twin Share Balcony Fantastica High Season',
        inclusion_highlights: 'test copy',
        status: 'draft',
        id: 117657,
        id_salesforce_external: 'a0s0I000006zVhGQAU',
        offer_id_salesforce_external: '0060I00000dafNxQAI',
        prices_count: 33,
        cost_price: 4432.65,
        cost_currency: 'AUD',
        qff_bonus_points: null,
        qff_bonus_description: null,
        regions: [],
        prices: [
          {
            currency_code: 'AUD',
            price: 5249,
            value: 6318,
            nightly_price: 0,
            nightly_value: 0,
          },
        ],
        sort_order: null,
        room_occupancy: 'Two Adults',
        deal_option_name: '1 Person Twin Share Balcony Fantastica High Season',
        flexible_nights: false,
        partnerships: [],
        is_exclusive: false,
        memberships: [],
        addons: [],
      },
      {
        _links: {},
        fk_tour_option_id: null,
        fk_tour_id: null,
        number_of_days: 21,
        name: '1 Person Twin Share Balcony Aurea High Season',
        description: '1 Person Twin Share Balcony Aurea High Season',
        inclusion_highlights: null,
        status: 'draft',
        id: 117655,
        id_salesforce_external: 'a0s0I000006zVhuQAE',
        offer_id_salesforce_external: '0060I00000dafNxQAI',
        prices_count: 33,
        cost_price: 5061.65,
        cost_currency: 'AUD',
        qff_bonus_points: null,
        qff_bonus_description: null,
        regions: [],
        prices: [
          {
            currency_code: 'AUD',
            price: 5979,
            value: 7088,
            nightly_price: 0,
            nightly_value: 0,
          },
        ],
        sort_order: 1,
        room_occupancy: 'Two Adults',
        deal_option_name: '1 Person Twin Share Balcony Aurea High Season',
        flexible_nights: false,
        partnerships: [],
        is_exclusive: false,
        memberships: [],
        addons: [],
      },
      {
        _links: {},
        fk_tour_option_id: null,
        fk_tour_id: null,
        number_of_days: 21,
        name: '1 Person Twin Share Suite Fantastica High Season',
        description: '1 Person Twin Share Suite Fantastica High Season',
        inclusion_highlights: 'test copy',
        status: 'draft',
        id: 117658,
        id_salesforce_external: 'a0s0I000006zVi4QAE',
        offer_id_salesforce_external: '0060I00000dafNxQAI',
        prices_count: 33,
        cost_price: 4636.65,
        cost_currency: 'AUD',
        qff_bonus_points: null,
        qff_bonus_description: null,
        regions: [],
        prices: [
          {
            currency_code: 'AUD',
            price: 5460,
            value: 6568,
            nightly_price: 0,
            nightly_value: 0,
          },
        ],
        sort_order: null,
        room_occupancy: 'Two Adults',
        deal_option_name: '1 Person Twin Share Suite Fantastica High Season',
        flexible_nights: false,
        partnerships: [],
        is_exclusive: false,
        memberships: [],
        addons: [],
      },
      {
        _links: {},
        fk_tour_option_id: null,
        fk_tour_id: null,
        number_of_days: 21,
        name: '1 Person Twin Share Aurea Suite High Season',
        description: '1 Person Twin Share Aurea Suite High Season',
        inclusion_highlights: 'test copy',
        status: 'draft',
        id: 117642,
        id_salesforce_external: 'a0s0I000006zVi9QAE',
        offer_id_salesforce_external: '0060I00000dafNxQAI',
        prices_count: 33,
        cost_price: 5257.15,
        cost_currency: 'AUD',
        qff_bonus_points: null,
        qff_bonus_description: null,
        regions: [],
        prices: [
          {
            currency_code: 'AUD',
            price: 6290,
            value: 7338,
            nightly_price: 0,
            nightly_value: 0,
          },
        ],
        sort_order: null,
        room_occupancy: 'Two Adults',
        deal_option_name: '1 Person Twin Share Aurea Suite High Season',
        flexible_nights: false,
        partnerships: [],
        is_exclusive: true,
        memberships: [],
        addons: [],
      },
      {
        _links: {},
        fk_tour_option_id: null,
        fk_tour_id: null,
        number_of_days: 21,
        name: '1 Person Twin Share Deluxe Suite Yacht Club High Season',
        description: '1 Person Twin Share Deluxe Suite Yacht Club High Season',
        inclusion_highlights: 'test copy',
        status: 'draft',
        id: 117660,
        id_salesforce_external: 'a0s0I000006zViJQAU',
        offer_id_salesforce_external: '0060I00000dafNxQAI',
        prices_count: 33,
        cost_price: 6098.65,
        cost_currency: 'AUD',
        qff_bonus_points: null,
        qff_bonus_description: null,
        regions: [],
        prices: [
          {
            currency_code: 'AUD',
            price: 6999,
            value: 8338,
            nightly_price: 0,
            nightly_value: 0,
          },
        ],
        sort_order: null,
        room_occupancy: 'Two Adults',
        deal_option_name:
          '1 Person Twin Share Deluxe Suite Yacht Club High Season',
        flexible_nights: false,
        partnerships: [],
        is_exclusive: false,
        memberships: [],
        addons: [],
      },
      {
        _links: {},
        fk_tour_option_id: '045ae9d0-5da7-11ea-a12f-0f40b52e158b',
        fk_tour_id: 'fdc100a0-5da6-11ea-a12f-0f40b52e158b',
        number_of_days: 21,
        name: '1 Person Twin Share Interior Fantastica Low Season',
        description: '1 Person Twin Share Interior Fantastica Low Season',
        inclusion_highlights: null,
        status: 'content-approved',
        id: 117568,
        id_salesforce_external: 'a0s0I000006zVGsQAM',
        offer_id_salesforce_external: '0060I00000dafNxQAI',
        prices_count: 33,
        cost_price: 3931.15,
        cost_currency: 'AUD',
        qff_bonus_points: null,
        qff_bonus_description: null,
        regions: [],
        prices: [
          {
            currency_code: 'AUD',
            price: 4599,
            value: 5708,
            nightly_price: 0,
            nightly_value: 0,
          },
        ],
        sort_order: 2,
        room_occupancy: 'Two Adults',
        deal_option_name: '1 Person Twin Share Interior Fantastica Low Season',
        flexible_nights: true,
        partnerships: [],
        is_exclusive: false,
        memberships: [],
        addons: [],
      },
      {
        _links: {},
        fk_tour_option_id: null,
        fk_tour_id: null,
        number_of_days: 21,
        name: '1 Person Twin Share Oceanview Fantastica Low Season',
        description: '1 Person Twin Share Oceanview Fantastica Low Season',
        inclusion_highlights: 'test copy',
        status: 'draft',
        id: 117662,
        id_salesforce_external: 'a0s0I000006zVH2QAM',
        offer_id_salesforce_external: '0060I00000dafNxQAI',
        prices_count: 33,
        cost_price: 4092.65,
        cost_currency: 'AUD',
        qff_bonus_points: null,
        qff_bonus_description: null,
        regions: [],
        prices: [
          {
            currency_code: 'AUD',
            price: 4789,
            value: 5908,
            nightly_price: 0,
            nightly_value: 0,
          },
        ],
        sort_order: null,
        room_occupancy: 'Two Adults',
        deal_option_name: '1 Person Twin Share Oceanview Fantastica Low Season',
        flexible_nights: false,
        partnerships: [],
        is_exclusive: false,
        memberships: [],
        addons: [],
      },
    ],
    images_count: 4,
    images: [],
    locations: [],
    flights_enabled: false,
    flights_cache_disabled: false,
    flights_max_arrival_time: null,
    flights_min_returning_departure_time: null,
    flight_regions: [],
    flight_destination_port: null,
    flights_warning_enabled: false,
    flights_warning_headline: null,
    flights_warning_popup_body: null,
    flexible_nights: false,
    insurance_countries: [],
    holiday_types: null,
    campaigns: null,
    display_value: true,
    subject_line: '',
    preheader: '',
    redemption_options: [],
    refunds_not_permitted: false,
    sf_brands: [],
    le_contracts_geo: null,
    payment_milestone: null,
    payment_method: 'Invoice',
    on_hold_settings: null,
    date_change_settings: null,
    latest_departure_date_change_allowed: null,
    offer_tile_inclusion_heading: null,
    offer_tile_inclusions: null,
    additional_description: null,
    campaign_type: null,
    days_before_check_in_changes_disallowed: 0,
  }
}

module.exports = {
  buildTourOffer,
}
