"use strict";

var OFFER_TYPE_HOTEL = 'hotel';
var OFFER_TYPE_TOUR = 'tour';
var OFFER_TYPE_LAST_MINUTE_HOTEL = 'last_minute_hotel';
var OFFER_TYPE_TACTICAL_AO_HOTEL = 'tactical_ao_hotel';
var LAST_MINUTE_CHECK_IN_LIMIT = 7;
module.exports = {
  OFFER_TYPE_HOTEL: OFFER_TYPE_HOTEL,
  OFFER_TYPE_TOUR: OFFER_TYPE_TOUR,
  OFFER_TYPE_LAST_MINUTE_HOTEL: OFFER_TYPE_LAST_MINUTE_HOTEL,
  OFFER_TYPE_TACTICAL_AO_HOTEL: OFFER_TYPE_TACTICAL_AO_HOTEL,
  LAST_MINUTE_CHECK_IN_LIMIT: LAST_MINUTE_CHECK_IN_LIMIT
};